/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#83d7b1",
        "on-primary-fixed-variant": "#005139",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#011d35",
        "primary-container": "#0b6e4f",
        "on-tertiary-fixed-variant": "#005049",
        "surface-container-high": "#e3e8f9",
        "surface-container-lowest": "#ffffff",
        "outline-variant": "#bec9c1",
        "secondary-fixed": "#d1e4ff",
        "tertiary-container": "#006d64",
        "background": "#f9f9ff",
        "on-secondary-fixed-variant": "#314863",
        "on-error-container": "#93000a",
        "surface-container-low": "#f1f3ff",
        "on-secondary-container": "#4b637e",
        "surface-dim": "#d4daea",
        "tertiary-fixed-dim": "#4fdbcc",
        "secondary-fixed-dim": "#b0c9e8",
        "secondary": "#49607c",
        "on-surface-variant": "#3f4943",
        "outline": "#6f7a73",
        "on-tertiary": "#ffffff",
        "error": "#ba1a1a",
        "surface-tint": "#056c4d",
        "primary": "#00543b",
        "on-primary": "#ffffff",
        "secondary-container": "#c7dfff",
        "on-tertiary-container": "#69f1e2",
        "surface-bright": "#f9f9ff",
        "inverse-surface": "#2a303d",
        "surface": "#f9f9ff",
        "on-background": "#161c27",
        "tertiary": "#00534c",
        "surface-variant": "#dde2f3",
        "primary-fixed": "#9ff4cc",
        "on-surface": "#161c27",
        "inverse-on-surface": "#ecf0ff",
        "on-error": "#ffffff",
        "on-tertiary-fixed": "#00201d",
        "tertiary-fixed": "#70f8e8",
        "primary-fixed-dim": "#83d7b1",
        "on-primary-fixed": "#002115",
        "error-container": "#ffdad6",
        "on-primary-container": "#98edc6",
        "surface-container-highest": "#dde2f3",
        "surface-container": "#e8eeff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "space-sm": "0.75rem",
        "space-xxs": "0.25rem",
        "space-xl": "2rem",
        "space-3xl": "4.5rem",
        "space-lg": "1.5rem",
        "space-2xl": "3rem",
        "gutter-desktop": "2rem",
        "gutter-mobile": "1rem",
        "margin-desktop": "3rem",
        "margin-mobile": "1.25rem",
        "max-content-width": "84rem",
        "space-md": "1rem",
        "space-xs": "0.5rem"
      },
      fontFamily: {
        "body-xl": ["Manrope", "sans-serif"],
        "body-sm": ["Manrope", "sans-serif"],
        "body-md": ["Manrope", "sans-serif"],
        "headline-md": ["Newsreader", "serif"],
        "label-md": ["Manrope", "sans-serif"],
        "headline-sm": ["Newsreader", "serif"],
        "headline-xl": ["Newsreader", "serif"],
        "label-sm": ["Manrope", "sans-serif"],
        "display-lg": ["Newsreader", "serif"],
        "label-lg": ["Manrope", "sans-serif"],
        "display-lg-mobile": ["Newsreader", "serif"],
        "headline-xl-mobile": ["Newsreader", "serif"]
      },
      fontSize: {
        "body-xl": ["1.125rem", { lineHeight: "1.75rem", letterSpacing: "-0.01em", fontWeight: "400" }],
        "body-sm": ["0.8125rem", { lineHeight: "1.25rem", letterSpacing: "0.01em", fontWeight: "400" }],
        "body-md": ["0.9375rem", { lineHeight: "1.5rem", letterSpacing: "0em", fontWeight: "400" }],
        "headline-md": ["1.75rem", { lineHeight: "2.25rem", letterSpacing: "-0.01em", fontWeight: "500" }],
        "label-md": ["0.8125rem", { lineHeight: "1.125rem", letterSpacing: "0.02em", fontWeight: "600" }],
        "headline-sm": ["1.25rem", { lineHeight: "1.75rem", letterSpacing: "0em", fontWeight: "600" }],
        "headline-xl": ["2.5rem", { lineHeight: "3rem", letterSpacing: "-0.015em", fontWeight: "500" }],
        "label-sm": ["0.6875rem", { lineHeight: "1rem", letterSpacing: "0.06em", fontWeight: "700" }],
        "display-lg": ["3.5rem", { lineHeight: "4rem", letterSpacing: "-0.02em", fontWeight: "400" }],
        "label-lg": ["0.9375rem", { lineHeight: "1.375rem", letterSpacing: "0.01em", fontWeight: "600" }],
        "display-lg-mobile": ["2.25rem", { lineHeight: "2.75rem", letterSpacing: "-0.015em", fontWeight: "400" }],
        "headline-xl-mobile": ["1.875rem", { lineHeight: "2.375rem", letterSpacing: "-0.01em", fontWeight: "500" }]
      }
    }
  },
  plugins: [],
};
