export const DEFAULT_DOCTOR_AVATAR = '/assets/doctor-collins.jpg';
export const DEFAULT_HOSPITAL_IMAGE = '/assets/aurora-hospital.jpg';

export const FALLBACK_DOCTORS = [
  {
    id: 1,
    hospitalId: 1,
    hospitalName: 'Aurora Medical Center',
    departmentId: 1,
    departmentName: 'Cardiology & Vascular Center',
    name: 'Dr. Michael Collins',
    title: 'Chief of Interventional Cardiology',
    specialty: 'Cardiology',
    licenseNumber: 'MD-WA-78219',
    experienceYears: 18,
    languages: 'English, Spanish',
    rating: 4.95,
    reviewCount: 142,
    consultationFee: 250.0,
    roomSuite: 'Pavilion B, Suite 410',
    bio: 'Fellowship-trained at Johns Hopkins Medicine. Specializes in minimally invasive structural heart valve repairs, complex coronary angioplasty, and cardiac rehabilitation.',
    education: "MD: Johns Hopkins University School of Medicine | Fellowship: Brigham and Women's Hospital",
    avatarUrl: '/assets/doctor-collins.jpg',
    availableThisWeek: true,
  },
  {
    id: 2,
    hospitalId: 1,
    hospitalName: 'Aurora Medical Center',
    departmentId: 2,
    departmentName: 'Comprehensive Neurology & Stroke Center',
    name: 'Dr. Sarah Wilson',
    title: 'Director of Neurovascular Therapeutics',
    specialty: 'Neurology',
    licenseNumber: 'MD-WA-65412',
    experienceYears: 14,
    languages: 'English, French',
    rating: 4.92,
    reviewCount: 98,
    consultationFee: 280.0,
    roomSuite: 'Tower A, Suite 305',
    bio: 'Dual-trained neurologist and clinical neuroscientist specializing in stroke recovery, acute migraine therapies, and movement disorders.',
    education: 'MD, PhD: Stanford University | Residency: UCSF Medical Center',
    avatarUrl: '/assets/doctor-wilson.jpg',
    availableThisWeek: true,
  },
  {
    id: 3,
    hospitalId: 2,
    hospitalName: "St. Jude Children's & Research Pavilion",
    departmentId: 3,
    departmentName: 'Neonatal & Advanced Pediatrics',
    name: 'Dr. Elena Rostova',
    title: 'Pediatric Pulmonology Specialist',
    specialty: 'Pediatrics',
    licenseNumber: 'MD-WA-90123',
    experienceYears: 11,
    languages: 'English, Russian',
    rating: 4.97,
    reviewCount: 184,
    consultationFee: 210.0,
    roomSuite: "Children's Wing, Suite 102",
    bio: 'Specializing in pediatric respiratory illnesses, cystic fibrosis clinics, and early childhood developmental screenings.',
    education: 'MD: University of Pennsylvania Perelman School of Medicine',
    avatarUrl: '/assets/doctor-rostova.jpg',
    availableThisWeek: true,
  },
  {
    id: 4,
    hospitalId: 1,
    hospitalName: 'Aurora Medical Center',
    departmentId: 4,
    departmentName: 'Orthopedics & Joint Replacement',
    name: 'Dr. Marcus Vance',
    title: 'Orthopedic Spine & Joint Reconstruction',
    specialty: 'Orthopedics',
    licenseNumber: 'MD-WA-43219',
    experienceYears: 16,
    languages: 'English',
    rating: 4.88,
    reviewCount: 115,
    consultationFee: 270.0,
    roomSuite: 'West Pavilion, Suite 520',
    bio: 'Board-certified orthopedic surgeon pioneer in muscle-sparing anterior hip replacement and endoscopic spinal disc decompressive surgeries.',
    education: 'MD: Harvard Medical School | Fellowship: Hospital for Special Surgery',
    avatarUrl: '/assets/doctor-vance.jpg',
    availableThisWeek: true,
  },
];
